import json
import os

leagues_data = {
  "source": "Opta Power Rankings (theanalyst.com)",
  "season": "2024-25",
  "snapshot_date": "2025-09-21",
  "note": "Rankings based on average Elo rating of clubs within each competition. Extended beyond top 50 to cover global verified leagues.",
  "leagues": [
    {"rank": 1, "name": "Premier League", "country": "England", "confederation": "UEFA"},
    {"rank": 2, "name": "Serie A", "country": "Italy", "confederation": "UEFA"},
    {"rank": 3, "name": "Bundesliga", "country": "Germany", "confederation": "UEFA"},
    {"rank": 4, "name": "La Liga", "country": "Spain", "confederation": "UEFA"},
    {"rank": 5, "name": "Ligue 1", "country": "France", "confederation": "UEFA"},
    {"rank": 6, "name": "Brasileirão Série A", "country": "Brazil", "confederation": "CONMEBOL"},
    {"rank": 7, "name": "Primeira Liga", "country": "Portugal", "confederation": "UEFA"},
    {"rank": 8, "name": "Eredivisie", "country": "Netherlands", "confederation": "UEFA"},
    {"rank": 9, "name": "Belgian Pro League", "country": "Belgium", "confederation": "UEFA"},
    {"rank": 10, "name": "Major League Soccer", "country": "USA", "confederation": "CONCACAF"},
    {"rank": 11, "name": "EFL Championship", "country": "England", "confederation": "UEFA"},
    {"rank": 12, "name": "Scottish Premiership", "country": "Scotland", "confederation": "UEFA"},
    {"rank": 13, "name": "Süper Lig", "country": "Turkey", "confederation": "UEFA"},
    {"rank": 14, "name": "Russian Premier League", "country": "Russia", "confederation": "UEFA"},
    {"rank": 15, "name": "Argentine Primera División", "country": "Argentina", "confederation": "CONMEBOL"},
    {"rank": 16, "name": "Liga MX", "country": "Mexico", "confederation": "CONCACAF"},
    {"rank": 17, "name": "Super League Greece", "country": "Greece", "confederation": "UEFA"},
    {"rank": 18, "name": "Czech First League", "country": "Czech Republic", "confederation": "UEFA"},
    {"rank": 19, "name": "Austrian Football Bundesliga", "country": "Austria", "confederation": "UEFA"},
    {"rank": 20, "name": "Swiss Super League", "country": "Switzerland", "confederation": "UEFA"},
    {"rank": 21, "name": "Ukrainian Premier League", "country": "Ukraine", "confederation": "UEFA"},
    {"rank": 22, "name": "Danish Superliga", "country": "Denmark", "confederation": "UEFA"},
    {"rank": 23, "name": "Eliteserien", "country": "Norway", "confederation": "UEFA"},
    {"rank": 24, "name": "Allsvenskan", "country": "Sweden", "confederation": "UEFA"},
    {"rank": 25, "name": "Ekstraklasa", "country": "Poland", "confederation": "UEFA"},
    {"rank": 26, "name": "J1 League", "country": "Japan", "confederation": "AFC"},
    {"rank": 27, "name": "K League 1", "country": "South Korea", "confederation": "AFC"},
    {"rank": 28, "name": "Saudi Pro League", "country": "Saudi Arabia", "confederation": "AFC"},
    {"rank": 29, "name": "Categoría Primera A", "country": "Colombia", "confederation": "CONMEBOL"},
    {"rank": 30, "name": "Chilean Primera División", "country": "Chile", "confederation": "CONMEBOL"},
    {"rank": 31, "name": "Uruguayan Primera División", "country": "Uruguay", "confederation": "CONMEBOL"},
    {"rank": 32, "name": "Ecuadorian Serie A", "country": "Ecuador", "confederation": "CONMEBOL"},
    {"rank": 33, "name": "Peruvian Primera División", "country": "Peru", "confederation": "CONMEBOL"},
    {"rank": 34, "name": "Paraguayan Primera División", "country": "Paraguay", "confederation": "CONMEBOL"},
    {"rank": 35, "name": "Bolivian Primera División", "country": "Bolivia", "confederation": "CONMEBOL"},
    {"rank": 36, "name": "Egyptian Premier League", "country": "Egypt", "confederation": "CAF"},
    {"rank": 37, "name": "South African Premier Division", "country": "South Africa", "confederation": "CAF"},
    {"rank": 38, "name": "Botola Pro", "country": "Morocco", "confederation": "CAF"},
    {"rank": 39, "name": "Tunisian Ligue Professionnelle 1", "country": "Tunisia", "confederation": "CAF"},
    {"rank": 40, "name": "Algerian Ligue Professionnelle 1", "country": "Algeria", "confederation": "CAF"},
    {"rank": 41, "name": "A-League Men", "country": "Australia", "confederation": "AFC"},
    {"rank": 42, "name": "Persian Gulf Pro League", "country": "Iran", "confederation": "AFC"},
    {"rank": 43, "name": "UAE Pro League", "country": "United Arab Emirates", "confederation": "AFC"},
    {"rank": 44, "name": "Qatar Stars League", "country": "Qatar", "confederation": "AFC"},
    {"rank": 45, "name": "Thai League 1", "country": "Thailand", "confederation": "AFC"},
    {"rank": 46, "name": "V.League 1", "country": "Vietnam", "confederation": "AFC"},
    {"rank": 47, "name": "Liga 1", "country": "Indonesia", "confederation": "AFC"},
    {"rank": 48, "name": "Malaysia Super League", "country": "Malaysia", "confederation": "AFC"},
    {"rank": 49, "name": "Indian Super League", "country": "India", "confederation": "AFC"},
    {"rank": 50, "name": "Costa Rican Primera División", "country": "Costa Rica", "confederation": "CONCACAF"},
    {"rank": 51, "name": "Serbian SuperLiga", "country": "Serbia", "confederation": "UEFA"},
    {"rank": 52, "name": "Croatian Football League", "country": "Croatia", "confederation": "UEFA"},
    {"rank": 53, "name": "Liga I", "country": "Romania", "confederation": "UEFA"},
    {"rank": 54, "name": "Nemzeti Bajnokság I", "country": "Hungary", "confederation": "UEFA"},
    {"rank": 55, "name": "Israeli Premier League", "country": "Israel", "confederation": "UEFA"},
    {"rank": 56, "name": "Cypriot First Division", "country": "Cyprus", "confederation": "UEFA"},
    {"rank": 57, "name": "Bulgarian First League", "country": "Bulgaria", "confederation": "UEFA"},
    {"rank": 58, "name": "Slovak First Football League", "country": "Slovakia", "confederation": "UEFA"},
    {"rank": 59, "name": "Slovenian PrvaLiga", "country": "Slovenia", "confederation": "UEFA"},
    {"rank": 60, "name": "Chinese Super League", "country": "China", "confederation": "AFC"},
    {"rank": 61, "name": "2. Bundesliga", "country": "Germany", "confederation": "UEFA"},
    {"rank": 62, "name": "Segunda División", "country": "Spain", "confederation": "UEFA"},
    {"rank": 63, "name": "Serie B", "country": "Italy", "confederation": "UEFA"},
    {"rank": 64, "name": "Ligue 2", "country": "France", "confederation": "UEFA"},
    {"rank": 65, "name": "Eerste Divisie", "country": "Netherlands", "confederation": "UEFA"},
    {"rank": 66, "name": "Segunda Liga", "country": "Portugal", "confederation": "UEFA"},
    {"rank": 67, "name": "Challenger Pro League", "country": "Belgium", "confederation": "UEFA"},
    {"rank": 68, "name": "Primera Nacional", "country": "Argentina", "confederation": "CONMEBOL"},
    {"rank": 69, "name": "Série B", "country": "Brazil", "confederation": "CONMEBOL"},
    {"rank": 70, "name": "Liga de Expansión MX", "country": "Mexico", "confederation": "CONCACAF"},
    {"rank": 71, "name": "USL Championship", "country": "USA", "confederation": "CONCACAF"},
    {"rank": 72, "name": "Canadian Premier League", "country": "Canada", "confederation": "CONCACAF"},
    {"rank": 73, "name": "Liga Nacional de Fútbol de Guatemala", "country": "Guatemala", "confederation": "CONCACAF"},
    {"rank": 74, "name": "Liga Nacional de Fútbol Profesional de Honduras", "country": "Honduras", "confederation": "CONCACAF"},
    {"rank": 75, "name": "Primera División de El Salvador", "country": "El Salvador", "confederation": "CONCACAF"},
    {"rank": 76, "name": "Venezuelan Primera División", "country": "Venezuela", "confederation": "CONMEBOL"},
    {"rank": 77, "name": "Nigerian Professional Football League", "country": "Nigeria", "confederation": "CAF"},
    {"rank": 78, "name": "Ghana Premier League", "country": "Ghana", "confederation": "CAF"},
    {"rank": 79, "name": "Kuwait Premier League", "country": "Kuwait", "confederation": "AFC"},
    {"rank": 80, "name": "Iraqi Premier League", "country": "Iraq", "confederation": "AFC"}
  ]
}

os.makedirs('data', exist_ok=True)
with open('data/leagues_opta.json', 'w', encoding='utf-8') as f:
    json.dump(leagues_data, f, ensure_ascii=False, indent=2)

print(f"Generated data/leagues_opta.json with {len(leagues_data['leagues'])} leagues.")
